name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Đã cập nhật lên v4

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Đã cập nhật lên v4
        with:
          node-version: 'lts/*'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run frontend tests
        run: npm run test
        working-directory: ./frontend

  build:
    needs: test # Chạy job 'test' trước
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Đã cập nhật lên v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Đã cập nhật lên v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # Đã cập nhật lên v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: taideptraiqua/ngoctai:latest # 
  open-pull-request:
    runs-on: ubuntu-latest
    needs: build
    # Job này chỉ nên chạy khi có push lên main, không phải từ pull_request
    # Vì bạn thường không tạo PR từ một PR khác
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Đã cập nhật lên v4
        with:
          # Cần token có quyền ghi để push commit mới
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Bước này là ví dụ nếu bạn muốn CI tạo ra một thay đổi nào đó
      # Ví dụ: cập nhật một file version, hoặc một file manifest
      # Nếu không có thay đổi nào được tạo ra, việc tạo PR sẽ không có ý nghĩa
      - name: Simulate a change (e.g., update version file)
        run: |
          echo "Build completed at $(date)" > build_status.txt
          git add build_status.txt
          git commit -m "CI: Update build status after successful Docker image push" || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6 # Đã cập nhật lên v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Nhánh mà PR sẽ được tạo từ.
          # Nếu bạn muốn tạo PR chứa các thay đổi được tạo ra bởi CI,
          # bạn cần tạo một nhánh mới hoặc push lên một nhánh tạm thời.
          # Ví dụ: tạo PR từ nhánh 'ci-automated-merge' tới 'main'
          branch: ci-automated-merge
          base: main # Nhánh đích mà PR sẽ merge vào
          title: "CI: Automated merge after Docker image build"
          body: |
            This pull request is automatically generated by the CI pipeline after a successful Docker image build and push.

            - **Docker Image Tag:** `taideptraiqua/ngoctai:latest`
            - **Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          commit-message: "CI: Automated changes for merge to main"
          # Nếu bạn muốn PR tự động merge khi các điều kiện được đáp ứng:
          # merge-method: squash
          # auto-merge: true
